// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin from "./routes/admin.tsx";
import * as $api_admin from "./routes/api/admin.ts";
import * as $api_users_confirm_account_email_ from "./routes/api/users/confirm-account/[email].ts";
import * as $api_users_sign_in from "./routes/api/users/sign-in.ts";
import * as $api_users_sign_up from "./routes/api/users/sign-up.ts";
import * as $groups_new_group from "./routes/groups/new-group.tsx";
import * as $index from "./routes/index.tsx";
import * as $users_sign_in from "./routes/users/sign-in.tsx";
import * as $users_sign_up from "./routes/users/sign-up.tsx";
import * as $Messages from "./islands/Messages.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin.tsx": $admin,
    "./routes/api/admin.ts": $api_admin,
    "./routes/api/users/confirm-account/[email].ts":
      $api_users_confirm_account_email_,
    "./routes/api/users/sign-in.ts": $api_users_sign_in,
    "./routes/api/users/sign-up.ts": $api_users_sign_up,
    "./routes/groups/new-group.tsx": $groups_new_group,
    "./routes/index.tsx": $index,
    "./routes/users/sign-in.tsx": $users_sign_in,
    "./routes/users/sign-up.tsx": $users_sign_up,
  },
  islands: {
    "./islands/Messages.tsx": $Messages,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
